add server install command

diff --git a/server_setup b/server_setup
--- a/server_setup
+++ b/server_setup
@@ -1,3 +1,50 @@
 #!/bin/bash
 
 # This script automates the setup of a basic web server environment
+
+: <<'END_COMMENT'
+if [[ $EUID -eq 0 ]]; then
+    if [[ -n "$SUDO_COMMAND" ]]; then
+        echo "Script is running with sudo."
+    else
+        echo "Script is running as root, but not with sudo."
+    fi
+else
+    echo "This script must be run as root or with sudo." >&2
+    exit 1
+fi
+END_COMMENT
+
+if [ ! $EUID -eq 0 ] || [ ! -n "$SUDO_COMMAND" ]; then
+	echo "This script must be run as root or with sudo." >&2
+	exit 1
+fi
+
+read -p "Choose server to install (1 for Apache2, 2 for Nginx): " choice
+
+if [ $choice == 1 ]; then
+	server_name="apache2"
+elif [ $choice == 2 ]; then
+	server_name="nginx"
+else
+	echo "Invalid input. Please select 1 for Apache2 and 2 for Nginx." >&2
+	exit 1
+fi
+
+echo " "
+echo "Updating Package Index"
+
+sudo apt update
+if [ $? -ne 0 ]; then
+	echo "Error: Failed to update packages." >&2
+	exit 1
+fi
+
+echo " "
+echo "Installing $server_name"
+
+sudo apt install "$server_name"
+if [ $? -ne 0 ]; then
+        echo "Error: Failed to install $server_name." >&2
+        exit 1
+fi
