create web page

diff --git a/server_setup b/server_setup
--- a/server_setup
+++ b/server_setup
@@ -26,7 +26,7 @@ done
 echo " "
 echo "Updating Package Index"
 
-sudo apt update
+sudo apt update -y
 if [ $? -ne 0 ]; then
 	echo "Error: Failed to update packages." >&2
 	exit 1
@@ -40,3 +40,31 @@ if [ $? -ne 0 ]; then
         echo "Error: Failed to install $server_name." >&2
         exit 1
 fi
+
+echo ""
+echo "Creating default index.html page"
+touch index.html
+if [ $? -ne 0 ]; then
+	echo "Server created"
+        echo "Error: Failed to create index.html" >&2
+        exit 1
+fi
+
+: << 'END_COMMENT'
+cat <<EOF > index.html
+<!DOCTYPE html>
+<html lang="en">
+<head>
+    <meta charset="UTF-8">
+    <meta name="viewport" content="width=device-width, initial-scale=1.0">
+    <title>Hello, World!</title>
+</head>
+<body>
+    <h1>Hello, World!</h1>
+    <p>This is a simple HTML page served by $(capitalize_first_letter "$server_name").</p>
+</body>
+</html>
+EOF
+
+echo "index.html file created"
+END_COMMENT
